version: 2.1
jobs:
  build-linux:
    docker:
      - image: node
    steps:
      - run:
          name: Generate app
          command: echo app > linux/app.linux
      - persist_to_workspace: 
          root: app
            # Must be relative path from root
          paths:
            - linux

  build-windows:
    docker:
      - image: node # use your imagination, using all linux/docker for ease-of-use
    steps:
      - run:
          name: Generate app
          command: echo app > linux/app.windows
      - persist_to_workspace: 
          root: app
            # Must be relative path from root
          paths:
            - windows

build-mac:
    docker:
      - image: node # use your imagination, using all linux/docker for ease-of-use
    steps:
      - run:
          name: Generate app
          command: echo app > linux/app.mac
      - persist_to_workspace: 
          root: app
            # Must be relative path from root
          paths:
            - mac

deploy:
    docker:
      - image: node # use your imagination, using all linux/docker for ease-of-use
    steps:
      - attach_workspace:
        # Must be absolute path or relative path from working_directory
          at: app
      - store_artifacts: # See circleci.com/docs/2.0/artifacts/ for more details.
          path: app
          destination: apps

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-linux
      - build-mac
      - build-windows
      - deploy:
          requires:
            - build-linux
            - build-mac
            - build-windows